spring.application.name=hospitalManagement

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.datasource.username=root
spring.datasource.password=root

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false
#
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

#security config-this will override the default value
#reading from in memory user
#spring.security.user.name=admin
#spring.security.user.password=admin

jwt.secret=aldknjfi2234kdfnvfvkl324kr3343mmklfkdfmfdfm22424kjiojpjj23

##enable oauth2
#spring.security.oauth2.client.registration.google.client-id=somendra23
#spring.security.oauth2.client.registration.google.client-secret=

